spring:
  datasource:
    node1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/es?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: ysl
      password: ysl123456
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      transaction-id-prefix: tran.
    consumer:
      bootstrap-servers: localhost:9092